### ISSUE TITLE
Scope field picker is displaying multiple select after popup validation

### ISSUE THREAD

**Issue by moustachu** [OpenSourcePolitics/decidim-module-socio_demographic_authorization_handler#4]
The screenshot speak for himself : 

<img width="870" alt="Capture d’écran 2019-12-16 à 16 05 08" src="https://user-images.githubusercontent.com/464350/70917615-f1bc2080-201d-11ea-9ae1-536f52172b5a.png">

Can be reproduced on https://dev.bosa.opensourcepolitics.eu/authorizations/new?handler=socio_demographic_authorization_handler

Sequence : 
- Open the scope picker popup
- Select a scope and validate the popup form
- The authorization form is updated (JS) with the selected value (in a select field) but leave the older select in place 

(on the screenshot, this sequence has been executed twice --> 3 select displayed)

**Comment by moustachu** [comment]
@Quentinchampenois This one could be tricky to fix ... 

It comes from this Helper method and the `root` parameter
https://github.com/OpenSourcePolitics/decidim/blob/0.18-merge/decidim-core/app/helpers/decidim/scopes_helper.rb#L42

And you use it like that : 
https://github.com/OpenSourcePolitics/decidim-module-socio_demographic_authorization_handler/blob/master/app/views/socio_demographic_authorization/_form.html.erb#L7

I did understand that you have to make it `nil` because : 
- if you remove it or set it to false, Decidim try to find a root scope from a participatory space
- you can't put the TOP scope ( "Global scope" ) since it does not exist in the scope hierarchy (most of the time, global scope is detected when the scope_id IS NULL ...)

But, I think the `root: nil` is causing some Javascript issues  

The Javascript use for this is here : 
https://github.com/OpenSourcePolitics/decidim/blob/0.18-merge/decidim-core/app/assets/javascripts/decidim/data_picker.js.es6

### Possible solution are : 
- Tweak the helper method to manage the root parameter for you need
- Fix the Javascript to manage the `root : nil` case (before, you need to be sure it comes from that and you might need help to understand the React / JS code)
- Add a "real" global scope (Belgium ?) to the scope hierarchy to be used in the form

@virgile-dev We need your input on the best solution here. Each of them could have unforeseen impact on the rest of the platform ...

**Comment by virgile-dev** [comment]
@moustachu @armandfardeau I'm getting pressured by the client to ship this.
I'd like to offer a 4th solution.

Admitting that the client has a simple use of the scopes, only one level, no child. (Which is going to be the case here, at least at firt). In this case we could replace the scope selector by a simple dropdown menu (this is a how Quentin's code was working in the first place).

**Comment by Quentinchampenois** [comment]
Hi ! I am looking about how to fix this issue. 
I was able to reproduce this issue on a master's clone and I think that I have some ideas about this behaviour
